server:
  port: 80

spring:
  application:
    name: api-gateway-server # 设置当前应用的名称。将来会在eureka中Application显示。将来需要使用该名称来获取路径
  cloud:
    gateway:
      routes:
        - id: gateway-provider
          uri: lb://FEIGN-PROVIDER
#          uri: http://localhost:8000/
          predicates:
            - Path=/goods/**

        - id: gateway-consumer
          uri: lb://FEIGN-CONSUMER
#          uri: http://localhost:9000/
          predicates:
            - Path=/order/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka